const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const root=path.join(__dirname,'matchday-studio'),ts=require(path.join(root,'node_modules/typescript')),React=require(path.join(root,'node_modules/react')),render=require(path.join(root,'node_modules/react-dom/server')).renderToStaticMarkup;
const original=Module._resolveFilename;
Module._resolveFilename=function(request,parent,...rest){if(request.startsWith('@/'))request=path.join(root,'src',request.slice(2));if(request.endsWith('.png?inline'))return path.resolve(path.dirname(parent.filename),request.slice(0,-7));return original.call(this,request,parent,...rest);};
require.extensions['.png']=(m,f)=>m.exports='data:image/png;base64,'+fs.readFileSync(f).toString('base64');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,f);
const {PosterSVG}=require(path.join(root,'src/components/formation/PosterSVG.tsx'));
const data={matchNumber:1,matchTitle:'Test <script>',matchDate:'2026-10-04',startTime:'20:00',endTime:'21:00',venue:'Doha & QFK',description:'Friendly',teamAName:'Team A',teamBName:'Team B',teamAPrimary:'#00f',teamASecondary:'#fff',teamAText:'#fff',teamAGK:'#000',teamBPrimary:'#fff',teamBSecondary:'#000',teamBText:'#000',teamBGK:'#000',teamAFormation:null,teamBFormation:null,players:[]};
for(const theme of ['stadium','matchday','split','premium','community','dynamic'])test('Cloud poster '+theme+' renders portable SVG with shared logo and escaped text',()=>{const s=render(React.createElement(PosterSVG,{data,theme}));assert.match(s,/viewBox="0 0 2400 3200"/);assert.match(s,/data:image\/png;base64,/);assert.doesNotMatch(s,/<foreignObject|<script>/);assert.match(s,/Doha &amp; QFK/);});
test('Export encodes before reporting completion and uses full-size SVG',()=>{const s=fs.readFileSync(path.join(root,'src/lib/poster-export.ts'),'utf8');assert.match(s,/clone.style.width = '2400px'/);assert.match(s,/clone.style.height = '3200px'/);assert.match(s,/await new Promise<Blob>/);assert.match(s,/PNG encoding failed/);});
test('App uses Finance theme loader and saved preference',()=>{assert.match(fs.readFileSync(path.join(root,'index.html'),'utf8'),/src="\.\.\/theme.js"/);assert.match(fs.readFileSync(path.join(root,'src/App.tsx'),'utf8'),/window.QFKTheme\?\.set/);});
test('Match form preserves edit values and requires key details',()=>{const {MatchForm}=require(path.join(root,'src/components/formation/MatchForm.tsx'));const s=render(React.createElement(MatchForm,{initial:{match_number:18,venue:'Doha'},formations:[],onSubmit:()=>{},onCancel:()=>{}}));assert.match(s,/type="number"[^>]*value="18"/);assert.ok((s.match(/required=""/g)||[]).length>=8);assert.match(s,/value="Doha"/);});
test('Poster scales to its container while keeping portrait proportions',()=>{const s=render(React.createElement(PosterSVG,{data,theme:'split'}));assert.match(s,/max-width:100%;height:auto;aspect-ratio:2400\/3200/);});
const {downloadPosterPNG}=require(path.join(root,'src/lib/poster-export.ts'));
test('PNG export waits for encoding and downloads full-size image',async()=>{
 const old={document:global.document,Image:global.Image,XMLSerializer:global.XMLSerializer};let encode,clicked=false,dimensions;
 const clone={style:{},setAttribute(){}};
 global.XMLSerializer=class{serializeToString(){return '<svg xmlns="http://www.w3.org/2000/svg"/>';}};
 global.Image=class{set src(v){queueMicrotask(()=>this.onload());}};
 global.document={createElement(tag){if(tag==='a')return{click(){clicked=true;}};return{getContext(){return{fillRect(){},drawImage(){}};},toBlob(cb){dimensions=[this.width,this.height];encode=cb;}};}};
 try{let done=false;const pending=downloadPosterPNG({cloneNode:()=>clone},'test.png').then(()=>done=true);await new Promise(r=>setImmediate(r));assert.equal(done,false);assert.equal(clicked,false);assert.deepEqual(dimensions,[2400,3200]);encode(new Blob(['png']));await pending;assert.equal(clicked,true);assert.equal(done,true);}finally{Object.assign(global,old);}
});
test('PNG export reports encoding failures instead of fake success',async()=>{
 const old={document:global.document,Image:global.Image,XMLSerializer:global.XMLSerializer};global.XMLSerializer=class{serializeToString(){return '<svg/>';}};global.Image=class{set src(v){queueMicrotask(()=>this.onload());}};global.document={createElement(){return{getContext(){return{fillRect(){},drawImage(){}};},toBlob(cb){cb(null);}};}};
 try{await assert.rejects(downloadPosterPNG({cloneNode:()=>({style:{},setAttribute(){}})},'test.png'),/PNG encoding failed/);}finally{Object.assign(global,old);}
});
const {placePlayer}=require(path.join(root,'src/lib/lineup-placement.ts'));
const {FormationBuilder}=require(path.join(root,'src/components/formation/FormationBuilder.tsx'));
const slotSet={A:[{position_code:'GK',label:'GK',x:50,y:90,display_order:0},{position_code:'ST',label:'ST',x:50,y:20,display_order:1}],B:[{position_code:'GK',label:'GK',x:50,y:90,display_order:0},{position_code:'CM',label:'CM',x:50,y:20,display_order:1}]};
const lineup=[{id:'a',player_id:'a',name:'Alice',jersey_number:1,team:'A',position:'GK',slot_index:0,status:'starter'},{id:'b',player_id:'b',name:'Bob',jersey_number:2,team:'A',position:'ST',slot_index:1,status:'starter'},{id:'c',player_id:'c',name:'Chris',jersey_number:3,team:'B',position:'CM',slot_index:1,status:'starter'},{id:'d',player_id:'d',name:'Dana',jersey_number:4,team:null,position:'GK',slot_index:0,status:'unassigned'}];
test('Lineup swaps occupied positions in the same team',()=>{const r=placePlayer(lineup,'a','A',1,slotSet);assert.equal(r[0].slot_index,1);assert.equal(r[0].position,'ST');assert.equal(r[1].slot_index,0);assert.equal(r[1].position,'GK');assert.equal(lineup[0].slot_index,0);});
test('Lineup swaps occupied positions across teams',()=>{const r=placePlayer(lineup,'a','B',1,slotSet);assert.equal(r[0].team,'B');assert.equal(r[0].position,'CM');assert.equal(r[2].team,'A');assert.equal(r[2].slot_index,0);assert.equal(r[2].position,'GK');});
test('Available player replaces starter and makes occupant available',()=>{const r=placePlayer(lineup,'d','A',1,slotSet);assert.equal(r[3].status,'starter');assert.equal(r[3].slot_index,1);assert.equal(r[1].team,null);assert.equal(r[1].status,'unassigned');});
test('Lineup moves to empty position and handles substitutes and unassignment',()=>{const r=placePlayer(lineup,'d','B',0,slotSet);assert.equal(r[3].status,'starter');assert.equal(r[3].position,'GK');const sub=placePlayer(r,'d','A',undefined,slotSet);assert.equal(sub[3].status,'substitute');assert.equal(sub[3].team,'A');const free=placePlayer(sub,'d',null,undefined,slotSet);assert.equal(free[3].status,'unassigned');assert.equal(free[3].team,null);});
test('Substitute replaces starter and displaced player takes substitute place',()=>{const subs=[...lineup,{...lineup[3],team:'B',status:'substitute'}].filter((p,i)=>i!==3);const r=placePlayer(subs,'d','A',0,slotSet);assert.equal(r[0].team,'B');assert.equal(r[0].status,'substitute');assert.equal(r[3].status,'starter');});
test('Invalid and unchanged placement do not mutate lineup',()=>{assert.equal(placePlayer(lineup,'a','A',0,slotSet),lineup);assert.equal(placePlayer(lineup,'missing','B',0,slotSet),lineup);assert.equal(placePlayer(lineup,'a','B',99,slotSet),lineup);});
test('Builder lists assigned and available roster players beside pitch on mobile',()=>{const props={players:lineup,roster:[{id:'extra',name:'Extra Player',jersey_number:8,is_active:true}],onChange:()=>{},teamAFormation:{positions:slotSet.A},teamBFormation:{positions:slotSet.B},teamAName:'A Team',teamBName:'B Team',teamAPrimary:'#00f',teamASecondary:'#fff',teamAText:'#fff',teamAGK:'#000',teamBPrimary:'#fff',teamBSecondary:'#00f',teamBText:'#000',teamBGK:'#000'};const html=render(React.createElement(FormationBuilder,props));assert.match(html,/Select Alice/);assert.match(html,/Select Dana/);assert.match(html,/Select Extra Player/);assert.match(html,/Pitch team/);assert.match(html,/grid-cols-\[112px_minmax\(0,1fr\)\]/);assert.doesNotMatch(html,/hidden md:block[^]*Select Alice/);assert.match(html,/data-lineup-target="slot"/);});
