-- DESIGN DRAFT ONLY. Not applied to any database.
-- All new names are independent of public finance tables.
create table public.matchday_players(id uuid primary key default gen_random_uuid(),name text not null,active boolean not null default true);
create table public.matchday_formations(id uuid primary key default gen_random_uuid(),name text not null,code text not null,active boolean not null default true);
create table public.matchday_positions(id uuid primary key default gen_random_uuid(),formation_id uuid not null references public.matchday_formations(id),label text not null,x numeric not null check(x between 0 and 100),y numeric not null check(y between 0 and 100),display_order integer not null);
create table public.matchday_matches(id uuid primary key default gen_random_uuid(),match_number integer not null unique check(match_number>0),title text not null,match_date date not null,start_time time not null,end_time time not null,venue text not null,description text,status text not null check(status in ('DRAFT','READY','ARCHIVED')),theme text not null,variant integer not null default 0,revision integer not null default 0,created_at timestamptz not null default now(),created_by text,updated_at timestamptz);
create table public.matchday_teams(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matchday_matches(id),side text not null check(side in ('A','B')),name text not null,primary_color text not null,secondary_color text not null,text_color text not null,goalkeeper_color text not null,formation_snapshot jsonb not null,unique(match_id,side));
create table public.matchday_roster(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matchday_matches(id),player_id uuid not null references public.matchday_players(id),side text check(side in ('A','B')),name_snapshot text not null,jersey_number integer check(jersey_number between 0 and 999),position_slot uuid,status text not null check(status in ('STARTER','SUBSTITUTE','UNASSIGNED')),unique(match_id,player_id));
create table public.matchday_poster_versions(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matchday_matches(id),theme text not null,variant integer not null,snapshot jsonb not null,file_path text,active boolean not null default false,created_at timestamptz not null default now(),created_by text);
-- Intentionally no grants, storage configuration, production policies or migrations.
-- A future persistence adapter must save an entire lineup atomically and check revision.
