(function(root){
 'use strict';
 const themes=["QFK Heritage","Midnight Doha","Royal Clash","Pearl Qatar","Emerald Arena","Black & Gold","Desert Lights","Maroon Fortress","Classic Matchday","Community Night","Burgundy Eclipse","Blue Thunder","Ivory Prestige","Copper Horizon","Emerald Crown","Silver Stadium","Crimson Spotlight","Ocean Floodlights","Golden Derby","Doha Celebration"].slice(0,5);
 const id=()=>globalThis.crypto.randomUUID();
 function formation(code='3-3-1') {const rows=code.split('-').map(Number);return {id:id(),name:code,code,active:true,slots:[{id:id(),label:'GK',x:50,y:88},...rows.flatMap((n,r)=>Array.from({length:n},(_,i)=>({id:id(),label:r===0?['LB','CB','RB'][i]||'DEF':r===rows.length-1?'ST':['LM','CM','RM'][i]||'MID',x:100*(i+1)/(n+1),y:68-r*48/Math.max(1,rows.length-1)})))]};}
 function createMatch(number,formations){return {id:id(),number,title:'Friday Community Match',date:'2026-09-18',start:'20:00',end:'21:00',venue:'Abu Hamour',description:'',status:'DRAFT',theme:(number+0)%themes.length,variant:0,createdAt:new Date().toISOString(),teams:['A','B'].map((side,i)=>({side,name:'Team '+side,color:i?'#f5f2e8':'#841c3c',secondary:'#d8b76b',text:i?'#111827':'#ffffff',goalkeeper:i?'#e4b32b':'#159c83',formation:structuredClone(formations[0])})),roster:[],posters:[]};}
 function move(match,playerId,side,slotId=null,status='STARTER'){const p=match.roster.find(p=>p.id===playerId);if(!p)throw Error('Player not found');const destination=match.roster.find(q=>q.id!==p.id&&q.side===side&&slotId&&q.slotId===slotId);const old={side:p.side,slotId:p.slotId,status:p.status};if(destination)Object.assign(destination,old);Object.assign(p,{side,slotId,status:side?status:'UNASSIGNED'});}
 function validate(match){const errors=[];for(const team of match.teams){for(const slot of team.formation.slots)if(!match.roster.some(p=>p.side===team.side&&p.slotId===slot.id&&p.status==='STARTER'))errors.push(team.name+': missing '+slot.label);const nums=new Set();for(const p of match.roster.filter(p=>p.side===team.side)){if(!p.name.trim())errors.push('Player name required');if(p.number!==''&&nums.has(String(p.number)))errors.push(team.name+': duplicate jersey '+p.number);nums.add(String(p.number));}}return errors;}
 function addPlayerToMatch(data,match,name,number=''){name=String(name).trim();if(!name)throw Error('Enter a player name.');if(number!==''&&(!Number.isInteger(Number(number))||Number(number)<0||Number(number)>999))throw Error('Jersey number must be 0–999.');let player=data.players.find(p=>p.name.trim().toLowerCase()===name.toLowerCase());if(player&&match.roster.some(p=>p.playerId===player.id))throw Error('This player is already in the match.');if(!player){player={id:id(),name,active:true};data.players.push(player);}const entry={id:id(),playerId:player.id,name:player.name,number:number===''?'':Number(number),side:null,slotId:null,status:'UNASSIGNED'};match.roster.push(entry);return entry;}
 function nextTheme(current,mode='random',random=Math.random){const count=themes.length,currentIndex=((Number(current)||0)%count+count)%count;if(mode==='ordered')return (currentIndex+1)%count;return (currentIndex+1+Math.floor(random()*(count-1)))%count;}
 const api={nextTheme,themes,id,formation,createMatch,move,validate,addPlayerToMatch};root.StudioModel=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
