const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');const M=require('./model.js');const context={window:{},Map};vm.runInNewContext(fs.readFileSync(__dirname+'/poster.js','utf8'),context);const P=context.window.StudioPoster;
test('five themes preserve updated lineup, escape names and have distinct output',()=>{const f=M.formation(),m=M.createMatch(14,[f]);m.roster=[{id:'p',name:'Jasim & Updated <17>',number:17,side:'A',slotId:f.slots[0].id,status:'STARTER'}];const outputs=[];for(let theme=0;theme<5;theme++){m.theme=theme;const svg=P.render(m);assert.match(svg,/Jasim &amp; Updated &lt;17&gt;/);assert.match(svg,/>17<\/text>/);assert.match(svg,new RegExp("assets/themes/"+String(theme+1).padStart(2,"0")+"\\.png"));assert.equal(svg,P.render(m));outputs.push(svg);}assert.equal(new Set(outputs).size,5);assert.match(outputs[1],/QFK<\/text>/);assert.match(outputs[2],/Royal Clash/);});
test('poster height grows to retain a large substitute list',()=>{const m=M.createMatch(1,[M.formation()]);for(let i=0;i<20;i++)m.roster.push({id:String(i),name:'Sub '+i,number:i,side:'A',status:'SUBSTITUTE'});const svg=P.render(m);assert.match(svg,/height="1872"/);assert.match(svg,/Sub 19/);});

test('all templates use builder match details and formations',()=>{const m=M.createMatch(32,[M.formation('2-3-1')]);m.date='2026-10-02';m.venue='Builder Venue';m.title='Builder Match';for(let theme=0;theme<5;theme++){m.theme=theme;const svg=P.render(m);assert.match(svg,/02 OCT 2026/);assert.match(svg,/BUILDER VENUE/);assert.match(svg,/FORMATION 2-3-1/);assert.match(svg,/BUILDER MATCH/);}});

test('each theme has a dedicated local background and leaves lineup data editable',()=>{const m=M.createMatch(1,[M.formation()]);for(let i=0;i<5;i++){m.theme=i;const svg=P.render(m);const art='assets/themes/'+String(i+1).padStart(2,'0')+'.png';assert.ok(fs.existsSync(__dirname+'/'+art),art);assert.match(svg,/poster-jersey-v2/);assert.match(svg,/poster-turf-v2/);assert.match(svg,/FORMATION 3-3-1/);assert.doesNotMatch(svg,/stadium-v1/);}});


test('five themes have distinct editorial copy while preserving builder fields',()=>{const m=M.createMatch(77,[M.formation('2-3-1')]);m.title='User Match';m.venue='User Venue';const phrases=['OUR CLUB. OUR PRIDE.','UNDER THE LIGHTS','THE ROYAL CLASH','THE BEAUTIFUL GAME','TOGETHER WE PLAY'];for(let i=0;i<5;i++){m.theme=i;const svg=P.render(m);assert.ok(svg.includes(phrases[i]));for(let j=0;j<5;j++)if(i!==j)assert.ok(!svg.includes(phrases[j]));assert.match(svg,/MATCH 77/);assert.match(svg,/USER MATCH/);assert.match(svg,/USER VENUE/);assert.match(svg,/FORMATION 2-3-1/);}});

