window.StudioPoster=(function(){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 const text=(x,y,s,size=24,color='#fff',anchor='middle',extra='')=>`<text x="${x}" y="${y}" font-size="${size}" font-weight="700" fill="${color}" text-anchor="${anchor}" ${extra}>${esc(s)}</text>`;
 function fit(x,y,s,width,size=22,color='#fff'){return text(x,y,s,Math.max(10,Math.min(size,width/(Math.max(1,String(s).length)*.61))),color);}
 function shirt(x,y,color,ink,trim,number,scale=1){return '<g transform="translate('+x+' '+y+') scale('+scale+')" filter="url(#shadow)"><g mask="url(#jersey-mask)"><rect x="-55" y="-45" width="110" height="110" fill="'+color+'"/><image href="assets/poster-jersey-v2.png" x="-55" y="-45" width="110" height="110" style="mix-blend-mode:multiply"/></g><image href="assets/qfk-logo.png" x="12" y="-17" width="13" height="16"/>'+text(0,14,number,typeof number==='string'&&number.length>2?20:32,ink)+'</g>';}
 function defs(){return `<defs><mask id="jersey-mask" mask-type="alpha"><image href="assets/poster-jersey-v2.png" x="-55" y="-45" width="110" height="110"/></mask><linearGradient id="fabric"><stop stop-color="#000" stop-opacity=".4"/><stop offset=".35" stop-color="#fff" stop-opacity=".03"/><stop offset=".5" stop-color="#fff" stop-opacity=".2"/><stop offset=".7" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".4"/></linearGradient><linearGradient id="grass" x2="0" y2="1"><stop stop-color="#298b3f"/><stop offset="1" stop-color="#123e1e"/></linearGradient><filter id="shadow" x="-30%" y="-30%" width="160%" height="160%"><feDropShadow dx="0" dy="6" stdDeviation="4" flood-opacity=".6"/></filter><filter id="grain"><feTurbulence type="fractalNoise" baseFrequency=".75" numOctaves="3" seed="12"/><feColorMatrix type="saturate" values="0"/><feComponentTransfer><feFuncA type="linear" slope=".09"/></feComponentTransfer><feBlend in="SourceGraphic" mode="soft-light"/></filter></defs>`;}
 function project(x,y,w,h,u,v){const width=w*(.82+.18*v);return [x+w/2+(u-.5)*width,y+v*h];}
 function pitch(x,y,w,h,border='#e2e8de'){const pt=(u,v)=>project(x,y,w,h,u,v).join(' '),path=points=>'M'+points.map(([u,v])=>pt(u,v)).join('L')+'Z';const outline=path([[0,0],[1,0],[1,1],[0,1]]);const clip='field-'+x+'-'+y;let out='<defs><clipPath id="'+clip+'"><path d="'+outline+'"/></clipPath><linearGradient id="field-light-'+x+'" x2="0" y2="1"><stop stop-color="#06160d" stop-opacity=".25"/><stop offset=".55" stop-color="#ffffff" stop-opacity=".03"/><stop offset="1" stop-color="#041b0d" stop-opacity=".3"/></linearGradient></defs><path d="'+outline+'" fill="#113a1c" stroke="'+border+'" stroke-width="3" filter="url(#shadow)"/><g clip-path="url(#'+clip+')"><image href="assets/turf-v1.png" x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" preserveAspectRatio="none"/><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" fill="url(#field-light-'+x+')"/></g><g fill="none" stroke="#ecf4dd" stroke-opacity=".8" stroke-width="2.4">';
 const box=(u,v,du,dv)=>'<path d="'+path([[u,v],[u+du,v],[u+du,v+dv],[u,v+dv]])+'"/>';out+=box(.025,.025,.95,.95)+'<path d="M'+pt(.025,.5)+'L'+pt(.975,.5)+'"/>'+box(.22,.025,.56,.16)+box(.35,.025,.3,.06)+box(.22,.815,.56,.16)+box(.35,.915,.3,.06);
 const ring=[];for(let i=0;i<=64;i++){const t=i/64*Math.PI*2;ring.push([.5+Math.cos(t)*.15,.5+Math.sin(t)*w/h*.15]);}out+='<path d="'+path(ring)+'"/>';
 for(const v of [.13,.5,.87]){const [cx,cy]=project(x,y,w,h,.5,v);out+='<circle cx="'+cx+'" cy="'+cy+'" r="2.6" fill="#ecf4dd"/>';}
 return out+'</g>';
 }
 function sharedGround(x,y,w,h,accent,theme){const pt=(u,v)=>project(x,y,w,h,u,v).join(' '),poly=pts=>'M'+pts.map(p=>pt(...p)).join('L')+'Z',outline=poly([[0,0],[1,0],[1,1],[0,1]]);let out='<defs><clipPath id="shared-field"><path d="'+outline+'"/></clipPath></defs><g clip-path="url(#shared-field)"><image href="assets/poster-turf-v2.png" x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" preserveAspectRatio="none"/>';
 if(theme===0||theme===3){out+='<rect x="'+x+'" y="'+y+'" width="'+w/2+'" height="'+h+'" fill="#640d2c" opacity=".72"/><rect x="'+(x+w/2)+'" y="'+y+'" width="'+w/2+'" height="'+h+'" fill="#342d23" opacity=".56"/>';}
 out+='</g><path d="'+outline+'" fill="none" stroke="'+accent+'" stroke-width="3"/><g fill="none" stroke="'+(theme===0||theme===3?'#e8cba5':'#eff5db')+'" stroke-width="2.7" stroke-opacity=".72">';
 const box=(u,v,du,dv)=>'<path d="'+poly([[u,v],[u+du,v],[u+du,v+dv],[u,v+dv]])+'"/>';out+=box(.018,.018,.964,.964)+'<path d="M'+pt(.5,.018)+'L'+pt(.5,.982)+'M'+pt(.018,.5)+'L'+pt(.982,.5)+'"/>';
 for(const offset of [0,.5]){out+=box(offset+.12,.018,.26,.16)+box(offset+.18,.018,.14,.065)+box(offset+.12,.822,.26,.16)+box(offset+.18,.917,.14,.065);const pts=[];for(let i=0;i<=64;i++){const t=i/64*Math.PI*2;pts.push([offset+.25+Math.cos(t)*.08,.5+Math.sin(t)*w/h*.08]);}out+='<path d="'+poly(pts)+'"/>';}
 return out+'</g>';}
 function lineup(m,team,x,y,w,h,accent,light=false){let out='';for(const slot of team.formation.slots){const p=m.roster.find(p=>p.side===team.side&&p.slotId===slot.id&&p.status==='STARTER');const u=.02+slot.x*.0096,v=.035+slot.y*.0089,[px,py]=project(70,y,1060,h,(x-70+w*u)/1060,v),scale=.97+.2*v,gk=slot.label.toUpperCase()==='GK';out+=shirt(px,py,gk?team.goalkeeper:team.color,gk?'#fff':team.text,team.secondary,p?.number??'—',scale);out+=fit(px,py+49,p?.name??'OPEN',w*.205,21,gk?'#fff':team.text)+'<rect x="'+(px-41)+'" y="'+(py+72)+'" width="82" height="29" rx="6" fill="#06111ded" stroke="'+accent+'" stroke-opacity=".6"/>'+text(px,py+93,slot.label,20,'#fff');}return out;}
 function brush(x,y,w,h,color){return `<path d="M${x+15} ${y+4}l${w-32} -4-6 10 23 4-13 13 5 ${h-40}-25 8 9 11-${w-34} 2 11-10-22-4 17-15-12-11 18-7Z" fill="${color}"/>`;}
 function prettyDate(s){const d=new Date(s+'T12:00:00Z');return Number.isNaN(d.getTime())?s:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).toUpperCase();}
 function prettyTime(s){const [h,min]=s.split(':').map(Number);return `${h%12||12}:${String(min||0).padStart(2,'0')} ${h>=12?'PM':'AM'}`;}
 function subs(m,team,x,y,w,accent){const ps=m.roster.filter(p=>p.side===team.side&&p.status==='SUBSTITUTE');let s=text(x,y,'SUBSTITUTES',16,accent,'start');if(!ps.length)return s+text(x,y+28,'—',18,'#eee','start');const lines=[];for(let i=0;i<ps.length;i+=2)lines.push(ps.slice(i,i+2).map(p=>`${p.number||'—'} ${p.name}`).join('  •  '));lines.forEach((v,i)=>s+=fit(x+w/2,y+29+i*25,v,w,19));return s;}
 const palettes=[['#650d2b','#c9a35b','#f4ebdd'],['#081b32','#e5b949','#f5f7fa'],['#1746d1','#c5dbff','#fff'],['#f3eee4','#771638','#293440'],['#103c2f','#c7ad77','#eee8d8'],['#101114','#d5b46a','#fff'],['#17232f','#af704b','#eadbc6'],['#4e1029','#bfc7ce','#fff'],['#14253d','#a7313d','#f0e7d5'],['#0b414b','#bea16a','#f2f0e8'],['#350921','#dfad72','#f5ebdf'],['#092a68','#52bdf5','#fff'],['#eee7d9','#91652f','#401a29'],['#27202b','#dc9569','#fff1dc'],['#082d24','#d4bf80','#f9f5df'],['#182330','#c7d0d9','#fff'],['#450d19','#efbd93','#fff'],['#073c4b','#77d9d6','#f7efdf'],['#231b12','#ecc868','#faf1d9'],['#2c1536','#d6b783','#fff']];
 const editorial=[
 {headline:'OUR CLUB. OUR PRIDE.',support:'ROOTED IN QATAR • UNITED BY FOOTBALL',footer:'THE QFK TRADITION',font:'Georgia,serif',qfk:158,headlineSize:42,spacing:3},
 {headline:'UNDER THE LIGHTS',support:'DOHA AFTER DARK • THE GAME COMES ALIVE',footer:'ONE NIGHT. ONE PASSION.',font:'Arial,sans-serif',qfk:120,headlineSize:62,spacing:5},
 {headline:'THE ROYAL CLASH',support:'TWO TEAMS • ONE PITCH • ALL HEART',footer:'BRING YOUR GAME',font:'Impact,Arial Black,sans-serif',qfk:150,headlineSize:65,spacing:1},
 {headline:'THE BEAUTIFUL GAME',support:'FOOTBALL • FRIENDSHIP • FINESSE',footer:'A QFK MATCHDAY IN DOHA',font:'Georgia,serif',qfk:142,headlineSize:46,spacing:2},
 {headline:'TOGETHER WE PLAY',support:'GOOD PLAYERS • BETTER PEOPLE • GREATER COMMUNITY',footer:'SAME GROUND. STRONGER TOGETHER.',font:'Arial,sans-serif',qfk:128,headlineSize:54,spacing:2}
 ];
 function render(m){const index=((Number(m.theme)||0)%5+5)%5,[base,accent,ink]=palettes[index],light=index===3||index===12,panorama=false;const style=editorial[index];const title=window.StudioModel?.themes?.[index]||['QFK Heritage','Midnight Doha','Royal Clash','Pearl Qatar','Emerald Arena','Black & Gold','Desert Lights','Maroon Fortress','Classic Matchday','Community Night','Burgundy Eclipse','Blue Thunder','Ivory Prestige','Copper Horizon','Emerald Crown','Silver Stadium','Crimson Spotlight','Ocean Floodlights','Golden Derby','Doha Celebration'][index];const subCount=Math.max(...m.teams.map(t=>Math.ceil(m.roster.filter(p=>p.side===t.side&&p.status==='SUBSTITUTE').length/2)));const H=1600+Math.max(0,subCount-2)*34;
 let out='<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="'+H+'" viewBox="0 0 1200 '+H+'" font-family="Arial,sans-serif" role="img" aria-label="'+esc(title)+' match '+esc(m.number)+'">'+defs()+'<defs><linearGradient id="title-metal" x2="0" y2="1"><stop stop-color="'+ink+'"/><stop offset=".45" stop-color="'+accent+'"/><stop offset=".6" stop-color="'+ink+'"/><stop offset="1" stop-color="'+accent+'"/></linearGradient><linearGradient id="readability" x2="0" y2="1"><stop stop-color="'+base+'" stop-opacity=".25"/><stop offset=".3" stop-color="'+base+'" stop-opacity="0"/><stop offset="1" stop-color="'+base+'" stop-opacity=".4"/></linearGradient></defs><image href="assets/themes/'+String(index+1).padStart(2,'0')+'.png" width="1200" height="1600" preserveAspectRatio="none"/><rect width="1200" height="1600" fill="url(#readability)"/>';
 if(H>1600)out+='<rect y="1400" width="1200" height="'+(H-1400)+'" fill="'+base+'"/>';
 const headerInk=light?'#48192e':ink;
 out+='<image href="assets/qfk-logo.png" x="80" y="55" width="95" height="95"/>';
 if(index===1)out+='<path d="M360 190H840" stroke="'+accent+'" stroke-width="2"/><path d="M100 350H225M975 350H1100" stroke="'+accent+'" stroke-width="2"/>';
 if(index===2)out+=brush(195,198,810,69,'#0a2579dd');
 if(index===3)out+='<path d="M300 195H900" stroke="#771638" stroke-width="1"/>';
 out+=text(600,176,'QFK',style.qfk,light?headerInk:'url(#title-metal)','middle','font-family="'+style.font+'" letter-spacing="'+style.spacing+'"'+(index===2?' font-style="italic"':'')+' filter="url(#shadow)"')+fit(600,252,style.headline,980,style.headlineSize,headerInk)+text(600,304,'MATCH '+m.number,38,light?headerInk:accent,'middle','letter-spacing="4"')+fit(600,343,style.support,970,22,headerInk)+fit(600,382,m.title.toUpperCase(),970,24,headerInk);
 const y=465,h=860,w=490,xs=[85,625];out+=sharedGround(70,y,1060,h,accent,index);
 if(panorama)out+=pitch(70,y,1060,h,accent,2)+'<path d="M600 '+(y+17)+'v'+(h-34)+'" stroke="#eee" stroke-width="2" opacity=".8"/>';
 m.teams.forEach((team,i)=>{const x=xs[i];out+='<rect x="'+x+'" y="410" width="'+w+'" height="52" fill="'+(light?'#f5eddfd9':'#061219d9')+'" stroke="'+accent+'" stroke-width="1"/>'+fit(x+w/2,447,team.name.toUpperCase(),w-30,31,light?'#48192e':ink);out+=lineup(m,team,x,y,w,h,accent,light)+text(x+w/2,1362,'FORMATION '+team.formation.code,25,light?'#48192e':ink);const substitutes=m.roster.filter(p=>p.side===team.side&&p.status==='SUBSTITUTE');if(substitutes.length){out+=text(x+w/2,1400,'SUBSTITUTES',18,light?'#48192e':accent);for(let n=0;n<substitutes.length;n+=2)out+=fit(x+w/2,1430+n/2*34,substitutes.slice(n,n+2).map(p=>(p.number||'—')+' '+p.name).join('  •  '),w,23,light?'#48192e':ink);}});
 const fy=H-102;out+='<rect x="75" y="'+(fy-32)+'" width="1050" height="58" rx="3" fill="'+(light?'#eee4d5e6':'#07121ce6')+'" stroke="'+accent+'" stroke-width="1"/>'+fit(240,fy+5,prettyDate(m.date),310,24,light?'#48192e':ink)+fit(600,fy+5,prettyTime(m.start)+' – '+prettyTime(m.end),365,24,light?'#48192e':ink)+fit(967,fy+5,m.venue.toUpperCase(),300,25,light?'#48192e':ink)+fit(600,H-43,style.footer,980,21,light?'#48192e':ink)+text(600,H-17,'QATAR FOOTBALL KOOTTAM',12,light?'#48192e':ink,'middle','letter-spacing="4"');return (out+'</svg>').replace(/id="([^"]+)"/g,(_,id)=>'id="'+id+'-'+index+'"').replace(/url\(#([^)]+)\)/g,(_,id)=>'url(#'+id+'-'+index+')');
 }
 const cache=new Map();async function embedAssets(svg){const paths=[...new Set([...svg.matchAll(/href="(assets\/[^"]+)"/g)].map(m=>m[1]))];for(const path of paths){if(!cache.has(path)){const response=await fetch(path);if(!response.ok)throw Error('Poster artwork could not be loaded.');const blob=await response.blob();const url=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});cache.set(path,url);}svg=svg.split(`href="${path}"`).join(`href="${cache.get(path)}"`);}return svg;}
 async function png(svg){svg=await embedAssets(svg);const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=2400;canvas.height=Math.round(2400*img.naturalHeight/img.naturalWidth);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('PNG generation failed')),'image/png'));}finally{URL.revokeObjectURL(url);}}
 return {render,png,embedAssets};
})();



